# Generated by Django 4.1.3 on 2023-02-16 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvengerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_image', models.CharField(blank=True, max_length=50, null=True)),
                ('user_wins', models.IntegerField(null=True)),
                ('user_losses', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_votes_team_1', models.IntegerField(default=0)),
                ('number_of_votes_team_2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField(null=True)),
                ('character_name', models.CharField(max_length=155)),
                ('character_picture', models.CharField(max_length=500)),
                ('character_extension', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengersassembleapi.character')),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_id', models.IntegerField(null=True)),
                ('comic_title', models.CharField(max_length=155)),
                ('comic_picture', models.CharField(max_length=500)),
                ('comic_extension', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(null=True)),
                ('movie_title', models.CharField(max_length=155)),
                ('movie_picture', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=155)),
                ('characters', models.ManyToManyField(through='avengersassembleapi.CharacterTeam', to='avengersassembleapi.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team', to='avengersassembleapi.avengeruser')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengersassembleapi.battle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_user_id', to='avengersassembleapi.avengeruser')),
                ('user_team_voted_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_vote_user_team', to='avengersassembleapi.userteam')),
            ],
        ),
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengersassembleapi.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengersassembleapi.avengeruser')),
            ],
        ),
        migrations.CreateModel(
            name='UserComic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengersassembleapi.comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengersassembleapi.avengeruser')),
            ],
        ),
        migrations.AddField(
            model_name='characterteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengersassembleapi.userteam'),
        ),
        migrations.AddField(
            model_name='battle',
            name='loser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_loser', to='avengersassembleapi.userteam'),
        ),
        migrations.AddField(
            model_name='battle',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='avengersassembleapi.userteam'),
        ),
        migrations.AddField(
            model_name='battle',
            name='team_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='avengersassembleapi.userteam'),
        ),
        migrations.AddField(
            model_name='battle',
            name='user_being_challenged',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_being_challenged', to='avengersassembleapi.avengeruser'),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_winner', to='avengersassembleapi.userteam'),
        ),
        migrations.AddField(
            model_name='avengeruser',
            name='favorite_comics',
            field=models.ManyToManyField(through='avengersassembleapi.UserComic', to='avengersassembleapi.comic'),
        ),
        migrations.AddField(
            model_name='avengeruser',
            name='favorite_movies',
            field=models.ManyToManyField(through='avengersassembleapi.UserMovie', to='avengersassembleapi.movie'),
        ),
        migrations.AddField(
            model_name='avengeruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
