# Generated by Django 4.1.3 on 2022-12-02 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvengerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=50)),
                ('profile_image', models.CharField(blank=True, max_length=50, null=True)),
                ('favorite_comics', models.CharField(blank=True, max_length=100, null=True)),
                ('favorite_movies', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team', to='avengersassembleapi.avengeruser')),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle', to='avengersassembleapi.battle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_user_id', to='avengersassembleapi.avengeruser')),
                ('user_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_vote_user_team', to='avengersassembleapi.userteam')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_user_team', to='avengersassembleapi.userteam')),
            ],
        ),
        migrations.CreateModel(
            name='BattleRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_1', to='avengersassembleapi.avengeruser')),
                ('opponent_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_2', to='avengersassembleapi.avengeruser')),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team_1', to='avengersassembleapi.userteam'),
        ),
        migrations.AddField(
            model_name='battle',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team_2', to='avengersassembleapi.userteam'),
        ),
    ]
